### ISSUE TITLE
build fails, can't resolve dependencies

### ISSUE THREAD

**Issue by alegrm** [AKSW/FOX#12]
Hi, I failed to build FOX following directions in the README. I guess there is some repository missing in the pom? the error is below, any sugestion?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:19.164s
[INFO] Finished at: Fri Sep 04 09:31:33 UTC 2015
[INFO] Final Memory: 18M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fox: Could not resolve dependencies for project org.aksw:fox:jar:2.3.0: The following artifacts could not be resolved: com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.5.1, com.fasterxml.jackson.core:jackson-core:jar:0.5.1, com.fasterxml.jackson.core:jackson-databind:jar:0.5.1, com.github.jsonld-java.jsonld-java:jsonld-java-clerezza:bundle:0.5.1, org.apache.clerezza:rdf.core:jar:0.5.1, com.github.jsonld-java.jsonld-java:jsonld-java-rdf2go:bundle:0.5.1, com.github.jsonld-java.jsonld-java:jsonld-java-sesame:bundle:0.5.1, org.openrdf.sesame:sesame-model:jar:0.5.1, org.openrdf.sesame:sesame-rio-api:jar:0.5.1: Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.5.1 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR]

**Comment by jitpack-io** [comment]
Hi,
had just a quick look but it could be that you need to put jitpack as the last repository in the list. that way it won't check all your dependencies against it

**Comment by alegrm** [comment]
Hi, changing the order of repositories has no effect. 
I notice (in the ERROR) there is something weird about the versions of the artifacts it is trying to download. The only correct version is the one for jsonld (0.5.1). The others (jackson-croe, fasterxml,.. etc) are not correct (also 0.5.1). I don't understand why is using those versions. 
Moreover there is *bundle* type in this artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.5.1 ... any idea?

**Comment by renespeck** [comment]
Hi, 

thanks jitpack-io for that info. 

0.5.1 was available but not anymore. I don't know why. I will fix this soon (update the version.)

Thanks for the report.

**Comment by alegrm** [comment]
I changed the version for jsonld to 0.6.0 and it works.

**Comment by rpietzsch** [comment]
``<version>0.6.0</version>``produces same error for me:

```
[ERROR] Failed to execute goal on project fox: 
Could not resolve dependencies for project org.aksw:fox:jar:2.3.0: 
The following artifacts could not be resolved: 
com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.6.0, 
com.github.jsonld-java.jsonld-java:jsonld-java-clerezza:bundle:0.6.0, 
com.github.jsonld-java.jsonld-java:jsonld-java-rdf2go:bundle:0.6.0: 
Could not find artifact com.github.jsonld-java.jsonld-java:jsonld-java:bundle:0.6.0 in jitpack.io (https://jitpack.io) -> [Help 1]
```

**Comment by renespeck** [comment]
That is strange, since I updated to 0.6.0 2h ago and it was build:
https://travis-ci.org/AKSW/FOX/builds/79603029

**Comment by renespeck** [comment]
I have added the jar in a local repo in foxs repo. So everything should work again.

Thanks for the reports.
