### ISSUE TITLE
Dependencies from the Illinois' Maven Repo have been moved

### ISSUE THREAD

**Issue by shatu** [AKSW/FOX#5]
Hello guys,

It seems like the following dependencies have been moved from the Illinois' maven repository. Kindly, either update your pom file and target it to the updated jars or host the previous jars on the AKSW repo., in case the new versions of the jars are not compatible with the source code.

[dependency]
            [groupId] edu.illinois.cs.cogcomp [/groupId]
            [artifactId] illinois-ner-extended [/artifactId]
            [version] 2.8 [/version]
[/dependency]

[dependency]
            [groupId] edu.illinois.cs.cogcomp [/groupId]
            [artifactId] IllinoisNerExtended [/artifactId]
            [version] 2.7 [/version]
            [classifier] models-conll [/classifier]
[/dependency]

[dependency]
            [groupId] edu.illinois.cs.cogcomp [/groupId]
            [artifactId] IllinoisNerExtended [/artifactId]
            [version] 2.7 [/version]
            [classifier] models-ontonotes [/classifier]
[/dependency]

Thanks,
Shashank

EDIT: Sorry, forgot to add emoji.. " :sob: " :stuck_out_tongue_closed_eyes:

**Comment by renespeck** [comment]
Hi Shashank, 

thank you very much for the report. 
I made an update and everything should work now. :wink:
